### ISSUE TITLE
How to visualize tfrecords-data?

### ISSUE THREAD

**Issue by t-tanakas** [google-research/meta-dataset#101]
I think the tfrecords data is in binary format, but I want to visualize it in a human-readable format. 
If anyone can visualize it, please tell me how to do that.

**Comment by lamblin** [comment]
tfrecords are not specific to meta-dataset, they're a format used by tensorflow and related software, so these issues are probably not the best place to get help.
I'd suggest you start with [this tutorial](https://www.tensorflow.org/tutorials/load_data/tfrecord).
