### ISSUE TITLE
Why does meta-dataset need tfrecords and not use the normal image files or something else?

### ISSUE THREAD

**Issue by brando90** [google-research/meta-dataset#107]
Why does meta-dataset need tfrecords and not use the normal image files or something else?

related: https://github.com/brando90/pytorch-meta-dataset/issues/22

**Comment by vdumoulin** [comment]
The reason why is twofold:
1. We are using `tf.data.Dataset` to sample episodes, which itself relies on the `tfrecord` format.
2. There's a fairly large latency cost to storing each image into its own file rather than grouping them into (sharded) binary files.
