### ISSUE TITLE
request to upload tfrecords data set somewhere for us please?

### ISSUE THREAD

**Issue by brando90** [google-research/meta-dataset#109]
e.g. I've used zenodo https://zenodo.org/.

Main challenges right now for me are mscoco and imagenet ilsvrc_2012

**Comment by brando90** [comment]
this https://github.com/google-research/meta-dataset/blob/main/doc/dataset_conversion.md is actually very hard to actually make it work

**Comment by brando90** [comment]
related: https://github.com/google-research/meta-dataset/issues/111

**Comment by vdumoulin** [comment]
Unfortunately this is not feasible, since not all datasets used by Meta-Dataset are licensed under terms which allow redistributing the data.
