### ISSUE TITLE
Leaderboard DIPA [CVPR 2024]

### ISSUE THREAD

**Issue by rashindrie** [google-research/meta-dataset#120]
Hi,

@lamblin  @eleniTriantafillou  @vdumoulin 
Could you please add the following results to the leaderboard notebook?

### Training on ImageNet (Train) only:

```
dipa_imagenet_df = pd.DataFrame(
    columns=['mean (%)', '95% CI', '# episodes'],
    index=datasets
)
dipa_imagenet_df['# episodes'] = 600
dipa_imagenet_df.loc[1:, ['mean (%)', '95% CI']] = [
   [71.4, 0.9],
   [84.3, 1.2],
   [86.7, 1.0],
   [88.2, 0.9],
   [87.1, 0.6],
   [74.6, 0.8],
   [61.4, 1.2],
   [97.4, 0.4],
   [88.9, 1.0],
   [65.2, 1.0],
]
dipa_imagenet_df
```

Also, please add the following to the last line of the `imagenet_dfs` dict:
`'DIPA': dipa_imagenet_df`

### Training on all datasets:
```
dipa_all_df = pd.DataFrame(
    columns=['mean (%)', '95% CI', '# episodes'],
    index=datasets
)
dipa_all_df['# episodes'] = 600
dipa_all_df.loc[1:, ['mean (%)', '95% CI']] = [
   [70.9 ,1.0],
  [84.7 , 1.1],
  [86.3 , 1.0],
  [90.8 , 0.8],
  [88.6 , 0.5],
  [75.3 , 0.8],
  [66.6 , 1.1],
  [97.9 , 0.3],
  [91.3 , 1.0],
  [64.8 , 1.0],
]
dipa_all_df
```

Also, please add the following to the last line of the `all_dfs` dict:
`'DIPA': dipa_all_df`

### Reference
```
ref = ("Perera, R., & Halgamuge, S. (2024)",
       "Rashindrie Perera, Saman Halgamuge;"
       "[Discriminative Sample-Guided and Parameter-Efficient Feature Space Adaptation for Cross-Domain Few-Shot Learning]"
       "(https://arxiv.org/abs/2403.04492);"
       "To appear in CVPR 2024.")
references.append(ref)
```

Article:  [Discriminative Sample-Guided and Parameter-Efficient Feature Space Adaptation for Cross-Domain Few-Shot Learning](https://arxiv.org/abs/2403.04492) [Accepted to CVPR 2024]
GitHub Repo: https://github.com/rashindrie/DIPA

Thank you!

**Comment by rashindrie** [comment]
@lamblin @eleniTriantafillou @vdumoulin Would you be able to assist with this? 

Thank you! :)

**Comment by vdumoulin** [comment]
Hi Rashindrie, really sorry about the delay, I'll try to get to it this week.

**Comment by vdumoulin** [comment]
Done! Thank you for your patience, and congratulations on your paper being accepted at CVPR 2024!
