### ISSUE TITLE
bug in dataset_to_records.py

### ISSUE THREAD

**Issue by jfb54** [google-research/meta-dataset#14]
In dataset_to_records.py, lines 958 and 959 say:
    with tf.gfile.GFile(imagelabels_path, 'r') as f:
      labels = loadmat(f)['labels'][0]
However, loadmat takes a string as a file_name, not a file handle, so just replace the above 2 lines with this single line:
    labels = loadmat(imagelabels_path)['labels'][0]

**Comment by lamblin** [comment]
Is this failing for you? Do you have an error message?

I tried it and it worked. Besides, the [API reference](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html) says:
> Can also pass open file-like object.

The .mat file still needs to be opened in binary mode, though.

**Comment by jfb54** [comment]
Yes, it absolutely failed for me unless I passed in the string. For what it is worth, I am using Python 3.5.

I thought I checked the API docs, but obviously the docs are clear that a file handle will work.

Perhaps the real error was that binary mode was not specified and for some reason when a string instead of a file handle is passed binary mode was assumed??? If you still need more info, I can run the code again tomorrow and get you the error message.

**Comment by lamblin** [comment]
If you could try with `GFile(..., 'rb')` and report back, it would be really helpful.

Indeed, I expect that if a string is passed, then the file would be open in the correct mode.

**Comment by jfb54** [comment]
I'll report back tomorrow.

**Comment by jfb54** [comment]
With the code as is, the following error message occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 138, in <module>
    tf.app.run(main)
  File "/homes/mlghomes/jfb54/tf/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/homes/mlghomes/jfb54/tf/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/homes/mlghomes/jfb54/tf/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 134, in main
    converter.convert_dataset()
  File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 547, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 959, in create_dataset_specification_and_records
    labels = loadmat(f)['labels'][0]
  File "/homes/jfb54/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 217, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/homes/jfb54/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 72, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/homes/jfb54/.local/lib/python3.5/site-packages/scipy/io/matlab/miobase.py", line 225, in get_matfile_version
    mopt_ints = np.ndarray(shape=(4,), dtype=np.uint8, buffer=mopt_bytes)
TypeError: a bytes-like object is required, not 'str'

When changing line 958 to:
    with tf.gfile.GFile(imagelabels_path, 'rb') as f:
all works fine.
So, the actual bug was not opening the file in binary mode. Of course, passing in a string to loadmat also works.

**Comment by lamblin** [comment]
Thanks for confirming, the fix is on its way.

**Comment by YudiZhangGithub** [comment]
> With the code as is, the following error message occurs: Traceback (most recent call last): File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main "**main**", mod_spec) File "/usr/lib/python3.5/runpy.py", line 85, in _run_code exec(code, run_globals) File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 138, in tf.app.run(main) File "/homes/mlghomes/jfb54/tf/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "/homes/mlghomes/jfb54/tf/lib/python3.5/site-packages/absl/app.py", line 300, in run _run_main(main, args) File "/homes/mlghomes/jfb54/tf/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main sys.exit(main(argv)) File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 134, in main converter.convert_dataset() File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 547, in convert_dataset self.create_dataset_specification_and_records() File "/homes/jfb54/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 959, in create_dataset_specification_and_records labels = loadmat(f)['labels'][0] File "/homes/jfb54/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 217, in loadmat MR, _ = mat_reader_factory(f, **kwargs) File "/homes/jfb54/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 72, in mat_reader_factory mjv, mnv = get_matfile_version(byte_stream) File "/homes/jfb54/.local/lib/python3.5/site-packages/scipy/io/matlab/miobase.py", line 225, in get_matfile_version mopt_ints = np.ndarray(shape=(4,), dtype=np.uint8, buffer=mopt_bytes) TypeError: a bytes-like object is required, not 'str'
> 
> When changing line 958 to: with tf.gfile.GFile(imagelabels_path, 'rb') as f: all works fine. So, the actual bug was not opening the file in binary mode. Of course, passing in a string to loadmat also works.

thanks!
