### ISSUE TITLE
cu_birds dataset converter does not use bounding box information

### ISSUE THREAD

**Issue by jfb54** [google-research/meta-dataset#16]
The cu_birds dataset comes with bounding boxes, but it is not utilized in the converter. Since several other datasets use bounding box info, this dataset should also be cropped to the bounding boxes.

**Comment by lamblin** [comment]
We decided to use bounding boxes only for the following datasets:
- In MSCOCO, multiple objects are present in different parts of the image.
- In Aircraft, there could be more than one aircraft in some images, and we wanted to crop the copyright text part at the bottom of images.

For other datasets, we opted not to use them, which makes the problem more challenging.
We will clarify the usage of bounding boxes in the article or supplementary material.

**Comment by jfb54** [comment]
Sure. That is fine. Yes, would be good to clarify in the paper somewhere.
