### ISSUE TITLE
ValueError when converting Aircraft dataset

### ISSUE THREAD

**Issue by peymanbateni** [google-research/meta-dataset#18]
When converting the aircraft dataset, the following error stops the conversion:

`python -m meta_dataset.dataset_conversion.convert_datasets_to_records --dataset=aircraft --aircraft_data_root=../DATA/fgvc-aircraft-2013b --splits_root=../SPLITS --records_root=../RECORDS
W0820 00:59:02.069226 140401200199424 deprecation_wrapper.py:119] From /home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py:138: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0820 00:59:02.069815 140401200199424 deprecation_wrapper.py:119] From /home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py:447: The name tf.gfile.IsDirectory is deprecated. Please use tf.io.gfile.isdir instead.

W0820 00:59:02.069998 140401200199424 deprecation_wrapper.py:119] From /home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py:448: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0820 00:59:02.070303 140401200199424 deprecation_wrapper.py:119] From /home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py:131: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

I0820 00:59:02.070400 140401200199424 convert_datasets_to_records.py:133] Creating FGVC-Aircraft Benchmark specification and records in directory ../RECORDS/aircraft...
I0820 00:59:02.070508 140401200199424 dataset_to_records.py:585] Attempting to read splits from ../SPLITS/aircraft_splits.json...
W0820 00:59:02.071086 140401200199424 deprecation_wrapper.py:119] From /home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py:586: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

I0820 00:59:02.071225 140401200199424 dataset_to_records.py:592] Unsuccessful.
I0820 00:59:02.071769 140401200199424 dataset_to_records.py:195] Created splits with 70 train, 15 validation and 15 test classes.
W0820 00:59:02.071928 140401200199424 deprecation_wrapper.py:119] From /home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py:1086: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

I0820 00:59:02.072792 140401200199424 dataset_to_records.py:641] Saving new splits for dataset aircraft at ../SPLITS/aircraft_splits.json...
W0820 00:59:02.072932 140401200199424 deprecation_wrapper.py:119] From /home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py:642: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

I0820 00:59:02.073486 140401200199424 dataset_to_records.py:644] Done.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 138, in <module>
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 134, in main
    converter.convert_dataset()
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 546, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1159, in create_dataset_specification_and_records
    assert class_names == all_classes
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by lamblin** [comment]
Thanks for reporting this problem, I have a good idea what is happening. I'll submit a fix soon.
