### ISSUE TITLE
Missing 'path_to_is_a' and 'path_to_words' files

### ISSUE THREAD

**Issue by jfb54** [google-research/meta-dataset#2]
I am attempting to generate the splits for the ILSVRC2012 dataset by running convert_datasets_to_records.py. There are numerous reasons why the code in the repo won't run, but chief among them is that two required files are missing. Here is an excerpt from imagenet_specification.py with TODOs on the file locations:

```python
# TODO(etriantafillou): validate file location.
tf.flags.DEFINE_string(
    'path_to_is_a',
    '',
    'Path to the file containing is-a relationships (parent, child) pairs.')

# TODO(etriantafillou): validate file location.
tf.flags.DEFINE_string(
    'path_to_words',
    '',
    'Path to the file containing (synset, word description) pairs.')
```

Is it possible to get the files added to the repo or a pointer to where they might be?

**Comment by lamblin** [comment]
Thanks for the interest!
We are working on instructions to generate the records files, including what original data to download.
For now, you can download them from:
- http://www.image-net.org/archive/wordnet.is_a.txt
- http://www.image-net.org/archive/words.txt

The latest master will look for them inside `FLAGS.ilsvrc_2012_data_root` by default, and other issues have been fixed, so you may be able to run it.

**Comment by jfb54** [comment]
Thanks!
