### ISSUE TITLE
When I use fungi dataset for tutorials, I got 'ValueError: Expected at least 2 images per class.' 

### ISSUE THREAD

**Issue by HayeonLee** [google-research/meta-dataset#20]
Hi, in Intro_to_Metadataset.ipynb, I executed (1) Episodic Mode iteratively 
(by changing codes from 
idx, episode = next(iterate_dataset(dataset_episodic, 1))
to
for idx, episode in iterate_dataset(dataset_episodic, 1):
)

Then I got error message 'ValueError: Expected at least 2 images per class.' 
![image](https://user-images.githubusercontent.com/19198395/63686172-2cfecd80-c83c-11e9-9d56-b4ba4b192a54.png)

If I excluded 'fungi' dataset , then this error is solved.
I guess there are some bugs related with 'fungi' dataset.
How can I solve this problem?

**Comment by HayeonLee** [comment]
I found it is code bug. 
Please modify code in dataset_conversion/dataset_to_records.py, class FungiConverter 
class_paths = class_filepaths[class_label] -->
class_paths = class_filepaths[class_id]

**Comment by HayeonLee** [comment]
@lamblin 
Thanks! 
Can you tell me when a modified version will be uploaded?

**Comment by lamblin** [comment]
The current conversion code for fungi still has another mistake, that makes it generate splits that are different from those reported.
Fix in progress.

**Comment by lamblin** [comment]
It should be OK now.
