### ISSUE TITLE
Would it be possible to have the semantic class labels in addition to the numbered labels when reading from a dataset?

### ISSUE THREAD

**Issue by peymanbateni** [google-research/meta-dataset#26]
Since cross-modal models are becoming widely used, is there an option to collect the semantic label of the class in addition to the numbered label? If not, would it be possible to add this capability?

**Comment by lamblin** [comment]
This is a good point.
For now, we have added the text labels (as originally provided) in the [`*_splits.json` files](https://github.com/google-research/meta-dataset/tree/master/meta_dataset/dataset_conversion/splits) that are generated during the dataset conversion. Our numeric labels are just the index of each class in the order of train, valid, then test.

A more direct mapping is also generated in the `dataset_spec.json` files, we will share a reference version of them in this repo as well.

The exceptions are `vgg_flower` and `traffic_sign`, as the original source of the dataset did not provide meaningful semantic labels.

Adding a text field in the tf examples is something we are considering for a future version of the conversion scripts.

**Comment by peymanbateni** [comment]
Thanks for the input.

I believe the problem right now isn't lack of a mapping from class number to semantic label (as there are ways around that, but it is great to hear that the mappings are already stored in some capacity). **The problem is that for each task produced, we cannot obtain the label for the original dataset, and hence, it's unclear which mapping to use to go from numbered labels to semantic labels.**

I may of course be unaware of such capability if it exists already. Please let me know! Thanks!

**Comment by lamblin** [comment]
Indeed, the current episodic pipeline selects one dataset for each episode, but does not keep that information. I agree it would be useful.

In case you would like to play with it before we can, you could zip each dataset created by `create_dataset_input_pipeline` [here](https://github.com/google-research/meta-dataset/blob/master/meta_dataset/data/pipeline.py#L363) with a constant stream of strings (the source name), and then use a `map_fn` that handles that case.
Or maybe `create_dataset_input_pipeline` could have that option directly.

**Comment by lamblin** [comment]
I believe this feature has been added in de390790d0456c0906138d63274381ea0c1a9d09 and the intro notebook has been upgraded to showcase it in 34057b260883908bffb56d09d19df708f1596056. Feel free to reopen if this does not fully address your concern.
