### ISSUE TITLE
Data splits for all datasets to reproduce the paper results

### ISSUE THREAD

**Issue by cys4** [google-research/meta-dataset#4]
Thank you for releasing this interesting work!
I've found this benchmark would be useful for our research.
Can I get exact splits for all 10 datasets to reproduce the results in the paper?
Or could you let me know where I can get that information in this code?

**Comment by lamblin** [comment]
Thanks for your interest.
You can follow the progression of the user documentation in PR #3, the instructions to download and convert the datasets is already there.
During the conversion process, for most datasets, the existing classes are shuffled (with a fixed random seed), and a given number are chosen to be meta-train, -valid, and -test. You can have a look at the specifics in `meta_dataset/dataset_conversion/dataset_to_records.py`.

**Comment by cys4** [comment]
Thanks! I'll look into it.
