### ISSUE TITLE
Can you provide lists of train, val, and test sets on ImageNet?

### ISSUE THREAD

**Issue by HobbitLong** [google-research/meta-dataset#44]
Hi,

Thanks for open-sourcing this nice dataset!

I wonder if you can release lists of train, val and test categories of ImageNet? So I can write my own data loading function which should be much faster when working on PyTorch.

**Comment by lamblin** [comment]
The list of WordNet IDs corresponding to the meta-splits can be extracted from [ilsvrc_2012_dataset_spec.json](https://github.com/google-research/meta-dataset/blob/master/meta_dataset/dataset_conversion/dataset_specs/ilsvrc_2012_dataset_spec.json).

The keys of `images_per_class["TRAIN"]` (for instance) should give you the WordNet IDs for the meta-train split. We consider only the leaves, so you can ignore the IDs that do not correspond to an image directory of the ILSVRC dataset.

You can also check `split_subgraphs["TRAIN"]` for the whole graph structure (including which nodes are leaves), and the words associated with each category.

**Comment by HobbitLong** [comment]
Thank you very much, @lamblin! I will have a try and get back.

**Comment by jfb54** [comment]
@HobbitLong For what it is worth, the meta-dataset reader performance is quite good when called from pytorch. Here is the implementation that we wrote for CNAPs: https://github.com/cambridge-mlg/cnaps/blob/master/src/meta_dataset_reader.py

**Comment by lamblin** [comment]
Please also note that if you want to reproduce episodes from the same distribution as ours, especially for evaluation purposes, you would also need to reproduce:
- filtering out duplicates images from ImageNet, like in [`ImagenetConverter._create_data_spec`](https://github.com/google-research/meta-dataset/blob/master/meta_dataset/dataset_conversion/dataset_to_records.py#L1502-L1509)
- the sampling logic for the composition of episodes, accessible from [`EpisodeDescriptionSampler.sample_episode_description`](https://github.com/google-research/meta-dataset/blob/master/meta_dataset/data/sampling.py#L424), which uses
- the WordNet hierarchy for the ImageNet classes, where the validation and test root have been cut off (for instance, the version serialized in ilsvrc_2012_dataset_spec.json).

Most of that code is available as pure Python (no TensorFlow) in this repo, so you may be able to just copy/paste most of it (as long as the licence is respected of course).

**Comment by HobbitLong** [comment]
@lamblin,

Thanks a lot for this reminder.

I have used my own dataloader for pre-training (standard classification) purpose, and then used your dataloader here to do meta-testing, which should replicates the testing scenario.

I will close this issue now!
