### ISSUE TITLE
Fungi dataset link not working.

### ISSUE THREAD

**Issue by brjathu** [google-research/meta-dataset#48]
I am trying to convert the datasets, but could not able to download Fungi dataset. Could you provide an alternative link?

**Comment by lamblin** [comment]
It seems that the hosting service, [data.deic.dk](http://data.deic.dk), is down. It is possible it may stay down and be replaced by [sciencedata.dk](https://sciencedata.dk/), which seems to be a newer version of the project from the same group (see [this blog post](http://frederik.orellana.dk/does-denmark-need-a-science-cloud/) for instance).

Unfortunately, the [terms of use](https://github.com/visipedia/fgvcx_fungi_comp#terms-of-use) prevent us from re-distributing the data.

We have reached out to the organizers of the FGVCx Fungi Classification Challenge to see if the data can be made available on a different platform, and will keep you updated.

**Comment by eleniTriantafillou** [comment]
The Fungi data has been uploaded to a new [location](https://labs.gbif.org/fgvcx/2018/), thanks to the organizers of the FGVCx Fungi Classification Challenge (as per the response in [this](https://github.com/visipedia/fgvcx_fungi_comp/issues/2) github issue). 

We haven't yet sanity-checked that it's identical to the data hosted in the original link, but sharing this update in case anyone is blocked by this.

**Comment by brjathu** [comment]
Thanks for the update :)

**Comment by lamblin** [comment]
The update in visipedia/fgvcx_fungi_comp#3 did not change the expected MD5 hash of the files, so these should be the exact same `.tgz` files as before.

I have re-downloaded the files and confirmed the MD5 is still the same.
