### ISSUE TITLE
Would it be possible to aggregate reported performances from work done on Meta-Dataset?

### ISSUE THREAD

**Issue by peymanbateni** [google-research/meta-dataset#49]
Meta-Datset is in many ways a much better benchmark for few-shot learning than the widely used mini/tiered ImageNet datasets. However, given the recent proposal of the work, finding state-of-the-art methods on the benchmark to compare to and potentially build on is a challenge of its own. To this end, would the community be interested in aggregating these works and their reported performances as part of this repository?

**Comment by lamblin** [comment]
Hi Peyman,
I agree it would be great to make this repo more about the benchmark and recent results, and maybe separate more what is about the methods and results of the ICLR article.

We could have a page (either in the source repo or the wiki) with a bibliography and leaderboard-like tables, and an Ipython notebook that could compute ranking and generate the tables when someone adds new results.

**Comment by peymanbateni** [comment]
Absolutely! And potentially even verify results through a server based submission system? In any case, I think even a simple table would be enormously useful to researchers working on this benchmark! Would we be able to set this up soon? :)

**Comment by peymanbateni** [comment]
Any updates on this front? :)

**Comment by peymanbateni** [comment]
A leaderboard has been fully formed at https://github.com/google-research/meta-dataset#training-on-all-datasets. Special thanks to the Google MetaDataset team for making this a reality!!!
