### ISSUE TITLE
Missing wordnet files for processing imaginet data

### ISSUE THREAD

**Issue by BrenoWSRCa** [google-research/meta-dataset#65]
Hi, thanks for sharing the work and for, well the amazing work.

I am trying to pre-process the ilsvrc_2012 data but it seems that two links (for the wordnet info) are no longer available. I searched for them in the image-net.org webpage, but with no success.

> Download the following two files into ILSVRC2012_img_train/:
>     http://www.image-net.org/archive/wordnet.is_a.txt
>     http://www.image-net.org/archive/words.txt

Do you have any other links to access those files? (Or can you share them somewhere else if it does not violate any license?)

Thanks in advance for your time.
And thanks again for sharing the dataset, I believe it is an important step towards more practical meta-learning. 

Best wishes,
Breno

**Comment by BrenoWSRCa** [comment]
The instructions I quoted is from the file [dataset_conversion.md#ilsvrc_2012](https://github.com/google-research/meta-dataset/blob/arxiv_v2_dev/doc/dataset_conversion.md#ilsvrc_2012).

**Comment by lamblin** [comment]
It appears the ImageNet website has changed the organization of its files.

If someone has a valid login to image-net.org, maybe they could try to see if these files are available to download in a different way and report it, we would be happy to update the instructions.

I am not sure whether we have the permission to share them directly, but some copies seem to exist on the Internet.

**Comment by BrenoWSRCa** [comment]
I got a login. It is an "external researcher who agreed with the terms of access" kind of login.

But still I was not able to find it.

This is the file structure that I have access so far:

 
![ImageNet download page](https://user-images.githubusercontent.com/3542657/117045069-78da6900-ace5-11eb-934e-70f77ecbdf76.png)

![ImageNet Large Scale Visual Recognition Challenge 2012 (ILSVRC2012) download page](https://user-images.githubusercontent.com/3542657/117045379-d373c500-ace5-11eb-927d-5de0a9709782.png)

**Comment by lamblin** [comment]
Thanks for the update.
If you would like the official source, I suggest you email the maintainers of image-net.org (imagenet.help.desk@gmail.com) and ask them about it.
Otherwise, the ones you can find with https://www.google.com/search?q=wordnet.is_a.txt seem to be correct.

**Comment by BrenoWSRCa** [comment]
Hey, I got a reply from them and those are the new paths for the files:

- http://www.image-net.org/data/wordnet.is_a.txt
- http://www.image-net.org/data/words.txt

Basically we only got to replace "archive" with "data" and all is good.

**Comment by lamblin** [comment]
Thanks for figuring it out!
I'll make the update.
