### ISSUE TITLE
Filing a bug for CrossTransformers code as suggested by Carl Doersch

### ISSUE THREAD

**Issue by quantacode** [google-research/meta-dataset#73]
Hi, When I run the following command for evaluating cross transformers

> **export EXPNAME=ctx
> export DATASET=omniglot
> python -m meta_dataset.train \
>   --is_training=False \
>   --records_root_dir=$RECORDS \
>   --summary_dir=${EXPROOT}/summaries/${EXPNAME}_eval_$DATASET \
>   --gin_config=meta_dataset/learn/gin/default/crosstransformer_imagenet.gin \
>   --gin_bindings="Trainer.experiment_name='${EXPNAME}'" \
>   --gin_bindings="Trainer.checkpoint_to_restore='experiments/checkpoints/ctx_pretr/ctx.ckpt'" \
>   --gin_bindings="benchmark.eval_datasets='$DATASET'"**  

I get the error:

> **File "/home/rajshekd/projects/FSG/CTX/meta_dataset/models/functional_backbones.py", line 369, in conv_bn
> depth[0],
> TypeError: 'int' object is not subscriptable**

Additionally in 

> **line 375 of File "/home/rajshekd/projects/FSG/CTX/meta_dataset/models/functional_backbones.py",
> input_rate is not defined**

Can you help resolve this?

**Comment by cdoersch** [comment]
@eleniTriantafillou Something funny is happening in functional backbones line 366:

https://github.com/google-research/meta-dataset/blob/main/meta_dataset/models/functional_backbones.py#L366

conv_bn seems to be calling itself.  I think there may be an issue with how the code is getting exported to github.

**Comment by lamblin** [comment]
I found something funny indeed, I'll send a fix soon.
Sorry about the delay.

**Comment by eleniTriantafillou** [comment]
Thank you so much Pascal! :)

**Comment by lamblin** [comment]
Done, thanks for the report!
