### ISSUE TITLE
Problem of Fungi dataset conversion to records 

### ISSUE THREAD

**Issue by hmcoo** [google-research/meta-dataset#79]
Hello,

During the conversion process, I experienced UnicodeDecode error, which is shown in below.

![utf-8 error](https://user-images.githubusercontent.com/36557350/149631805-93fae150-7dbf-402e-bc03-bb6d99d36547.png)

I figured out this problem is caused by:

![error_LI](https://user-images.githubusercontent.com/36557350/149632304-6a791116-e297-4b2a-9977-18b3a840f148.jpg)

Which means the File explorer cannot locate some Fungi classes (e,g, file name is: Hydnum umbilicatum ss auct. eur.).

My question is: Anyone went through similar problem with Fungi dataset? Everything worked well except Fungi dataset.

If not, I think something went wrong during extraction of tgz file using `tar xvf fungi_dataset`. 

Any recommends?

**Comment by xssdss** [comment]
I meet the same problem. Could you please provide a solution?
