### ISSUE TITLE
OOM when using maml_init_with_proto_imagenet.gin

### ISSUE THREAD

**Issue by crockwell** [google-research/meta-dataset#8]
Hello, I'm trying to replicate the result of proto-maml and when using the "maml_init_with_proto_imagenet.gin" config I am getting out of memory errors, even when using 4 12GB GPUs. I am using a pretrained maml_resnet that I trained without issue. Note I have been able to train knn, finetune, and maml using only 1 12GB GPU. Perhaps there is something silly I am missing? Or does this require more compute power? Thank you in advance!

The beginning of the error message looks like the following:
`2019-05-09 15:12:09.889884: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-05-09 15:12:10.128623: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.`

**Comment by crockwell** [comment]
Seems memory is only slightly over 12GB but current code is not setup for multiple GPUs.

**Comment by lamblin** [comment]
Indeed, we currently rely on passing the whole support or query set at once, as one batch.
Passing a smaller `DataConfig.image_height` could help avoid the OOM issue.
