### ISSUE TITLE
Typo in setup.py

### ISSUE THREAD

**Issue by jfb54** [google-research/meta-dataset#82]
The setup.py file wants to install etils version 0.7.0 or greater (https://github.com/google-research/meta-dataset/blob/main/setup.py#:~:text=absl%2Dpy%3E%3D0.7.0%27%2C-,%27etils%3E%3D0.7.0%27%2C,-%27gin%2Dconfig%3E%3D0.1.2), but the highest version available is 0.4.0.

Please fix.

**Comment by vdumoulin** [comment]
Fixed via 8fbfc63.
