### ISSUE TITLE
regarding metric learning based methods + MAML

### ISSUE THREAD

**Issue by vainaijr** [google-research/meta-dataset#9]
if prototypical networks when combined with maml give a higher accuracy, does this mean that other metric learning based methods, cosine similarity Vinyals et al. (2016), CNN-based relation module Sung et al. (2018), ridge regression Bertinetto et al. (2019), and
graph neural network Garcia & Bruna (2018) will also give better performance when combined with maml?

**Comment by lamblin** [comment]
It is very possible that some of these methods might benefit from training (some of) their parameters using MAML.
We did not try to adapt any of the methods you mention, but you're very welcome to try it out :)
