### ISSUE TITLE
Import Error in Intro_to_Metadataset.pynb with simclr package

### ISSUE THREAD

**Issue by letyrodridc** [google-research/meta-dataset#92]
Some errors occur when importing package of the notebook Intro_to_Metadataset.pynb after installing all the required packages in requirements.txt.

In example, I'm getting:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-b205b4ebaa47> in <module>
     13 from meta_dataset.data import dataset_spec as dataset_spec_lib
     14 from meta_dataset.data import learning_spec
---> 15 from meta_dataset.data import pipeline

/media/lety/tera/research-workspace/meta-dataset/meta_dataset/data/pipeline.py in <module>
     39 from meta_dataset.data import reader
     40 from meta_dataset.data import sampling
---> 41 from simclr import data_util
     42 from six.moves import zip
     43 import tensorflow.compat.v1 as tf

ImportError: cannot import name 'data_util'
```
The first error message was that `simclr` wasn't installed. I've used `pip install simclr` to solve it but some modules still missing.
Any idea? ty.

**Comment by lamblin** [comment]
The install script (setup.py) should download a version of it, so it can be imported, see https://github.com/google-research/meta-dataset/issues/62#issuecomment-839231697
