### ISSUE TITLE
"simclr" missing

### ISSUE THREAD

**Issue by lourencobt** [google-research/meta-dataset#96]
When I tried to use meta-dataset, I found that "simclr" is missing. However, I didn't found any information on how to import this module. I found that it refers to this repository https://github.com/google-research/simclr, but I would expect that you can add some more info about it somewhere.

**Comment by lamblin** [comment]
It should install if you execute the setup.py script, see https://github.com/google-research/meta-dataset/issues/62#issuecomment-839231697
